[project]
name = "mine-ops-platform"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "chdrPE", email = "121919989+chdrPE@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "asyncua>=2.0.1",
    "pandas>=3.0.6",
    "psycopg[binary]>=3.3.6",
    "scikit-learn>=1.9.1",
]

[project.scripts]
mine-ops-platform = "mine_ops_platform:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
